/**
 * API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unknown
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import Album from './model/Album';
import AlbumList from './model/AlbumList';
import AlbumListCover from './model/AlbumListCover';
import AuthToken from './model/AuthToken';
import Device from './model/Device';
import EventList from './model/EventList';
import EventRegistration from './model/EventRegistration';
import EventRegistrationAdminList from './model/EventRegistrationAdminList';
import EventRetrieve from './model/EventRetrieve';
import EventsCalenderJS from './model/EventsCalenderJS';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse2004 from './model/InlineResponse2004';
import InlineResponse2005 from './model/InlineResponse2005';
import InlineResponse2006 from './model/InlineResponse2006';
import InlineResponse2007 from './model/InlineResponse2007';
import InlineResponse2008 from './model/InlineResponse2008';
import InlineResponse2009 from './model/InlineResponse2009';
import MemberGroup from './model/MemberGroup';
import MemberList from './model/MemberList';
import Message from './model/Message';
import Order from './model/Order';
import Partner from './model/Partner';
import PartnerEvent from './model/PartnerEvent';
import PhotoCreate from './model/PhotoCreate';
import Pizza from './model/Pizza';
import ProfileEdit from './model/ProfileEdit';
import ActivemembersApi from './api/ActivemembersApi';
import DevicesApi from './api/DevicesApi';
import EventsApi from './api/EventsApi';
import MembersApi from './api/MembersApi';
import NotificationsApi from './api/NotificationsApi';
import PartnersApi from './api/PartnersApi';
import PhotosApi from './api/PhotosApi';
import PizzasApi from './api/PizzasApi';
import RegistrationsApi from './api/RegistrationsApi';
import TokenAuthApi from './api/TokenAuthApi';

/**
 * JS API client generated by OpenAPI Generator.<br>
 * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
 * <p>
 * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
 * <pre>
 * var ApiV1 = require('index'); // See note below*.
 * var xxxSvc = new ApiV1.XxxApi(); // Allocate the API class we're going to use.
 * var yyyModel = new ApiV1.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
 * and put the application logic within the callback function.</em>
 * </p>
 * <p>
 * A non-AMD browser application (discouraged) might do something like this:
 * <pre>
 * var xxxSvc = new ApiV1.XxxApi(); // Allocate the API class we're going to use.
 * var yyy = new ApiV1.Yyy(); // Construct a model instance.
 * yyyModel.someProperty = 'someValue';
 * ...
 * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
 * ...
 * </pre>
 * </p>
 * @module index
 * @version unknown
 */
export {
  /**
   * The ApiClient constructor.
   * @property {module:ApiClient}
   */
  ApiClient,
  /**
   * The Album model constructor.
   * @property {module:model/Album}
   */
  Album,
  /**
   * The AlbumList model constructor.
   * @property {module:model/AlbumList}
   */
  AlbumList,
  /**
   * The AlbumListCover model constructor.
   * @property {module:model/AlbumListCover}
   */
  AlbumListCover,
  /**
   * The AuthToken model constructor.
   * @property {module:model/AuthToken}
   */
  AuthToken,
  /**
   * The Device model constructor.
   * @property {module:model/Device}
   */
  Device,
  /**
   * The EventList model constructor.
   * @property {module:model/EventList}
   */
  EventList,
  /**
   * The EventRegistration model constructor.
   * @property {module:model/EventRegistration}
   */
  EventRegistration,
  /**
   * The EventRegistrationAdminList model constructor.
   * @property {module:model/EventRegistrationAdminList}
   */
  EventRegistrationAdminList,
  /**
   * The EventRetrieve model constructor.
   * @property {module:model/EventRetrieve}
   */
  EventRetrieve,
  /**
   * The EventsCalenderJS model constructor.
   * @property {module:model/EventsCalenderJS}
   */
  EventsCalenderJS,
  /**
   * The InlineResponse200 model constructor.
   * @property {module:model/InlineResponse200}
   */
  InlineResponse200,
  /**
   * The InlineResponse2001 model constructor.
   * @property {module:model/InlineResponse2001}
   */
  InlineResponse2001,
  /**
   * The InlineResponse2002 model constructor.
   * @property {module:model/InlineResponse2002}
   */
  InlineResponse2002,
  /**
   * The InlineResponse2003 model constructor.
   * @property {module:model/InlineResponse2003}
   */
  InlineResponse2003,
  /**
   * The InlineResponse2004 model constructor.
   * @property {module:model/InlineResponse2004}
   */
  InlineResponse2004,
  /**
   * The InlineResponse2005 model constructor.
   * @property {module:model/InlineResponse2005}
   */
  InlineResponse2005,
  /**
   * The InlineResponse2006 model constructor.
   * @property {module:model/InlineResponse2006}
   */
  InlineResponse2006,
  /**
   * The InlineResponse2007 model constructor.
   * @property {module:model/InlineResponse2007}
   */
  InlineResponse2007,
  /**
   * The InlineResponse2008 model constructor.
   * @property {module:model/InlineResponse2008}
   */
  InlineResponse2008,
  /**
   * The InlineResponse2009 model constructor.
   * @property {module:model/InlineResponse2009}
   */
  InlineResponse2009,
  /**
   * The MemberGroup model constructor.
   * @property {module:model/MemberGroup}
   */
  MemberGroup,
  /**
   * The MemberList model constructor.
   * @property {module:model/MemberList}
   */
  MemberList,
  /**
   * The Message model constructor.
   * @property {module:model/Message}
   */
  Message,
  /**
   * The Order model constructor.
   * @property {module:model/Order}
   */
  Order,
  /**
   * The Partner model constructor.
   * @property {module:model/Partner}
   */
  Partner,
  /**
   * The PartnerEvent model constructor.
   * @property {module:model/PartnerEvent}
   */
  PartnerEvent,
  /**
   * The PhotoCreate model constructor.
   * @property {module:model/PhotoCreate}
   */
  PhotoCreate,
  /**
   * The Pizza model constructor.
   * @property {module:model/Pizza}
   */
  Pizza,
  /**
   * The ProfileEdit model constructor.
   * @property {module:model/ProfileEdit}
   */
  ProfileEdit,
  /**
   * The ActivemembersApi service constructor.
   * @property {module:api/ActivemembersApi}
   */
  ActivemembersApi,
  /**
   * The DevicesApi service constructor.
   * @property {module:api/DevicesApi}
   */
  DevicesApi,
  /**
   * The EventsApi service constructor.
   * @property {module:api/EventsApi}
   */
  EventsApi,
  /**
   * The MembersApi service constructor.
   * @property {module:api/MembersApi}
   */
  MembersApi,
  /**
   * The NotificationsApi service constructor.
   * @property {module:api/NotificationsApi}
   */
  NotificationsApi,
  /**
   * The PartnersApi service constructor.
   * @property {module:api/PartnersApi}
   */
  PartnersApi,
  /**
   * The PhotosApi service constructor.
   * @property {module:api/PhotosApi}
   */
  PhotosApi,
  /**
   * The PizzasApi service constructor.
   * @property {module:api/PizzasApi}
   */
  PizzasApi,
  /**
   * The RegistrationsApi service constructor.
   * @property {module:api/RegistrationsApi}
   */
  RegistrationsApi,
  /**
   * The TokenAuthApi service constructor.
   * @property {module:api/TokenAuthApi}
   */
  TokenAuthApi,
};
