/**
 * API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unknown
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Album model module.
 * @module model/Album
 * @version unknown
 */
class Album {
  /**
   * Constructs a new <code>Album</code>.
   * @alias module:model/Album
   * @param _date {Date}
   */
  constructor(_date) {
    Album.initialize(this, _date);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, _date) {
    obj['date'] = _date;
  }

  /**
   * Constructs a <code>Album</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Album} obj Optional instance to populate.
   * @return {module:model/Album} The populated <code>Album</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Album();

      if (data.hasOwnProperty('pk')) {
        obj['pk'] = ApiClient.convertToType(data['pk'], 'Number');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'Date');
      }
      if (data.hasOwnProperty('hidden')) {
        obj['hidden'] = ApiClient.convertToType(data['hidden'], 'Boolean');
      }
      if (data.hasOwnProperty('shareable')) {
        obj['shareable'] = ApiClient.convertToType(data['shareable'], 'Boolean');
      }
      if (data.hasOwnProperty('accessible')) {
        obj['accessible'] = ApiClient.convertToType(data['accessible'], 'String');
      }
      if (data.hasOwnProperty('photos')) {
        obj['photos'] = ApiClient.convertToType(data['photos'], 'String');
      }
    }
    return obj;
  }
}

/**
 * @member {Number} pk
 */
Album.prototype['pk'] = undefined;

/**
 * @member {String} title
 */
Album.prototype['title'] = undefined;

/**
 * @member {Date} date
 */
Album.prototype['date'] = undefined;

/**
 * @member {Boolean} hidden
 */
Album.prototype['hidden'] = undefined;

/**
 * @member {Boolean} shareable
 */
Album.prototype['shareable'] = undefined;

/**
 * @member {String} accessible
 */
Album.prototype['accessible'] = undefined;

/**
 * @member {String} photos
 */
Album.prototype['photos'] = undefined;

export default Album;
