/**
 * API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unknown
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AlbumListCover from './AlbumListCover';

/**
 * The AlbumList model module.
 * @module model/AlbumList
 * @version unknown
 */
class AlbumList {
  /**
   * Constructs a new <code>AlbumList</code>.
   * @alias module:model/AlbumList
   * @param _date {Date}
   * @param cover {module:model/AlbumListCover}
   */
  constructor(_date, cover) {
    AlbumList.initialize(this, _date, cover);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, _date, cover) {
    obj['date'] = _date;
    obj['cover'] = cover;
  }

  /**
   * Constructs a <code>AlbumList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AlbumList} obj Optional instance to populate.
   * @return {module:model/AlbumList} The populated <code>AlbumList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AlbumList();

      if (data.hasOwnProperty('pk')) {
        obj['pk'] = ApiClient.convertToType(data['pk'], 'Number');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('date')) {
        obj['date'] = ApiClient.convertToType(data['date'], 'Date');
      }
      if (data.hasOwnProperty('hidden')) {
        obj['hidden'] = ApiClient.convertToType(data['hidden'], 'Boolean');
      }
      if (data.hasOwnProperty('shareable')) {
        obj['shareable'] = ApiClient.convertToType(data['shareable'], 'Boolean');
      }
      if (data.hasOwnProperty('accessible')) {
        obj['accessible'] = ApiClient.convertToType(data['accessible'], 'String');
      }
      if (data.hasOwnProperty('cover')) {
        obj['cover'] = AlbumListCover.constructFromObject(data['cover']);
      }
    }
    return obj;
  }
}

/**
 * @member {Number} pk
 */
AlbumList.prototype['pk'] = undefined;

/**
 * @member {String} title
 */
AlbumList.prototype['title'] = undefined;

/**
 * @member {Date} date
 */
AlbumList.prototype['date'] = undefined;

/**
 * @member {Boolean} hidden
 */
AlbumList.prototype['hidden'] = undefined;

/**
 * @member {Boolean} shareable
 */
AlbumList.prototype['shareable'] = undefined;

/**
 * @member {String} accessible
 */
AlbumList.prototype['accessible'] = undefined;

/**
 * @member {module:model/AlbumListCover} cover
 */
AlbumList.prototype['cover'] = undefined;

export default AlbumList;
