/**
 * API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unknown
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AlbumListCover model module.
 * @module model/AlbumListCover
 * @version unknown
 */
class AlbumListCover {
  /**
   * Constructs a new <code>AlbumListCover</code>.
   * @alias module:model/AlbumListCover
   * @param album {Number}
   */
  constructor(album) {
    AlbumListCover.initialize(this, album);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, album) {
    obj['album'] = album;
  }

  /**
   * Constructs a <code>AlbumListCover</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AlbumListCover} obj Optional instance to populate.
   * @return {module:model/AlbumListCover} The populated <code>AlbumListCover</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AlbumListCover();

      if (data.hasOwnProperty('pk')) {
        obj['pk'] = ApiClient.convertToType(data['pk'], 'Number');
      }
      if (data.hasOwnProperty('rotation')) {
        obj['rotation'] = ApiClient.convertToType(data['rotation'], 'Number');
      }
      if (data.hasOwnProperty('hidden')) {
        obj['hidden'] = ApiClient.convertToType(data['hidden'], 'Boolean');
      }
      if (data.hasOwnProperty('album')) {
        obj['album'] = ApiClient.convertToType(data['album'], 'Number');
      }
      if (data.hasOwnProperty('file')) {
        obj['file'] = ApiClient.convertToType(data['file'], 'String');
      }
    }
    return obj;
  }
}

/**
 * @member {Number} pk
 */
AlbumListCover.prototype['pk'] = undefined;

/**
 * This does not modify the original image file.
 * @member {module:model/AlbumListCover.RotationEnum} rotation
 */
AlbumListCover.prototype['rotation'] = undefined;

/**
 * @member {Boolean} hidden
 */
AlbumListCover.prototype['hidden'] = undefined;

/**
 * @member {Number} album
 */
AlbumListCover.prototype['album'] = undefined;

/**
 * @member {String} file
 */
AlbumListCover.prototype['file'] = undefined;

/**
 * Allowed values for the <code>rotation</code> property.
 * @enum {Number}
 * @readonly
 */
AlbumListCover['RotationEnum'] = {
  /**
   * value: 0
   * @const
   */
  0: 0,

  /**
   * value: 90
   * @const
   */
  90: 90,

  /**
   * value: 180
   * @const
   */
  180: 180,

  /**
   * value: 270
   * @const
   */
  270: 270,
};

export default AlbumListCover;
