/**
 * API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unknown
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventRetrieve model module.
 * @module model/EventRetrieve
 * @version unknown
 */
class EventRetrieve {
  /**
   * Constructs a new <code>EventRetrieve</code>.
   * @alias module:model/EventRetrieve
   * @param start {Date}
   * @param end {Date}
   * @param organiser {Number}
   * @param category {module:model/EventRetrieve.CategoryEnum} Alumni: Events organised for alumni, Education: Education focused events, Career: Career focused events, Leisure: borrels, parties, game activities etc., Association Affairs: general meetings or any other board related events, Other: anything else.
   * @param mapLocation {String} Location of Huygens: Heyendaalseweg 135, Nijmegen. Location of Mercator 1: Toernooiveld 212, Nijmegen. Not shown as text!!
   */
  constructor(start, end, organiser, category, mapLocation) {
    EventRetrieve.initialize(this, start, end, organiser, category, mapLocation);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, start, end, organiser, category, mapLocation) {
    obj['start'] = start;
    obj['end'] = end;
    obj['organiser'] = organiser;
    obj['category'] = category;
    obj['map_location'] = mapLocation;
  }

  /**
   * Constructs a <code>EventRetrieve</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventRetrieve} obj Optional instance to populate.
   * @return {module:model/EventRetrieve} The populated <code>EventRetrieve</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EventRetrieve();

      if (data.hasOwnProperty('pk')) {
        obj['pk'] = ApiClient.convertToType(data['pk'], 'Number');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('start')) {
        obj['start'] = ApiClient.convertToType(data['start'], 'Date');
      }
      if (data.hasOwnProperty('end')) {
        obj['end'] = ApiClient.convertToType(data['end'], 'Date');
      }
      if (data.hasOwnProperty('organiser')) {
        obj['organiser'] = ApiClient.convertToType(data['organiser'], 'Number');
      }
      if (data.hasOwnProperty('category')) {
        obj['category'] = ApiClient.convertToType(data['category'], 'String');
      }
      if (data.hasOwnProperty('registration_start')) {
        obj['registration_start'] = ApiClient.convertToType(
          data['registration_start'],
          'Date'
        );
      }
      if (data.hasOwnProperty('registration_end')) {
        obj['registration_end'] = ApiClient.convertToType(
          data['registration_end'],
          'Date'
        );
      }
      if (data.hasOwnProperty('cancel_deadline')) {
        obj['cancel_deadline'] = ApiClient.convertToType(
          data['cancel_deadline'],
          'Date'
        );
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = ApiClient.convertToType(data['location'], 'String');
      }
      if (data.hasOwnProperty('map_location')) {
        obj['map_location'] = ApiClient.convertToType(data['map_location'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'String');
      }
      if (data.hasOwnProperty('fine')) {
        obj['fine'] = ApiClient.convertToType(data['fine'], 'String');
      }
      if (data.hasOwnProperty('max_participants')) {
        obj['max_participants'] = ApiClient.convertToType(
          data['max_participants'],
          'Number'
        );
      }
      if (data.hasOwnProperty('num_participants')) {
        obj['num_participants'] = ApiClient.convertToType(
          data['num_participants'],
          'String'
        );
      }
      if (data.hasOwnProperty('user_registration')) {
        obj['user_registration'] = ApiClient.convertToType(
          data['user_registration'],
          'String'
        );
      }
      if (data.hasOwnProperty('registration_allowed')) {
        obj['registration_allowed'] = ApiClient.convertToType(
          data['registration_allowed'],
          'String'
        );
      }
      if (data.hasOwnProperty('no_registration_message')) {
        obj['no_registration_message'] = ApiClient.convertToType(
          data['no_registration_message'],
          'String'
        );
      }
      if (data.hasOwnProperty('has_fields')) {
        obj['has_fields'] = ApiClient.convertToType(data['has_fields'], 'String');
      }
      if (data.hasOwnProperty('is_pizza_event')) {
        obj['is_pizza_event'] = ApiClient.convertToType(
          data['is_pizza_event'],
          'String'
        );
      }
      if (data.hasOwnProperty('google_maps_url')) {
        obj['google_maps_url'] = ApiClient.convertToType(
          data['google_maps_url'],
          'String'
        );
      }
      if (data.hasOwnProperty('is_admin')) {
        obj['is_admin'] = ApiClient.convertToType(data['is_admin'], 'String');
      }
    }
    return obj;
  }
}

/**
 * @member {Number} pk
 */
EventRetrieve.prototype['pk'] = undefined;

/**
 * @member {String} title
 */
EventRetrieve.prototype['title'] = undefined;

/**
 * @member {String} description
 */
EventRetrieve.prototype['description'] = undefined;

/**
 * @member {Date} start
 */
EventRetrieve.prototype['start'] = undefined;

/**
 * @member {Date} end
 */
EventRetrieve.prototype['end'] = undefined;

/**
 * @member {Number} organiser
 */
EventRetrieve.prototype['organiser'] = undefined;

/**
 * Alumni: Events organised for alumni, Education: Education focused events, Career: Career focused events, Leisure: borrels, parties, game activities etc., Association Affairs: general meetings or any other board related events, Other: anything else.
 * @member {module:model/EventRetrieve.CategoryEnum} category
 */
EventRetrieve.prototype['category'] = undefined;

/**
 * If you set a registration period registration will be required. If you don't set one, registration won't be required. Prefer times when people don't have lectures, e.g. 12:30 instead of 13:37.
 * @member {Date} registration_start
 */
EventRetrieve.prototype['registration_start'] = undefined;

/**
 * If you set a registration period registration will be required. If you don't set one, registration won't be required.
 * @member {Date} registration_end
 */
EventRetrieve.prototype['registration_end'] = undefined;

/**
 * @member {Date} cancel_deadline
 */
EventRetrieve.prototype['cancel_deadline'] = undefined;

/**
 * @member {String} location
 */
EventRetrieve.prototype['location'] = undefined;

/**
 * Location of Huygens: Heyendaalseweg 135, Nijmegen. Location of Mercator 1: Toernooiveld 212, Nijmegen. Not shown as text!!
 * @member {String} map_location
 */
EventRetrieve.prototype['map_location'] = undefined;

/**
 * @member {String} price
 */
EventRetrieve.prototype['price'] = undefined;

/**
 * Fine if participant does not show up (at least €5).
 * @member {String} fine
 */
EventRetrieve.prototype['fine'] = undefined;

/**
 * @member {Number} max_participants
 */
EventRetrieve.prototype['max_participants'] = undefined;

/**
 * @member {String} num_participants
 */
EventRetrieve.prototype['num_participants'] = undefined;

/**
 * @member {String} user_registration
 */
EventRetrieve.prototype['user_registration'] = undefined;

/**
 * @member {String} registration_allowed
 */
EventRetrieve.prototype['registration_allowed'] = undefined;

/**
 * @member {String} no_registration_message
 */
EventRetrieve.prototype['no_registration_message'] = undefined;

/**
 * @member {String} has_fields
 */
EventRetrieve.prototype['has_fields'] = undefined;

/**
 * @member {String} is_pizza_event
 */
EventRetrieve.prototype['is_pizza_event'] = undefined;

/**
 * @member {String} google_maps_url
 */
EventRetrieve.prototype['google_maps_url'] = undefined;

/**
 * @member {String} is_admin
 */
EventRetrieve.prototype['is_admin'] = undefined;

/**
 * Allowed values for the <code>category</code> property.
 * @enum {String}
 * @readonly
 */
EventRetrieve['CategoryEnum'] = {
  /**
   * value: "alumni"
   * @const
   */
  alumni: 'alumni',

  /**
   * value: "education"
   * @const
   */
  education: 'education',

  /**
   * value: "career"
   * @const
   */
  career: 'career',

  /**
   * value: "leisure"
   * @const
   */
  leisure: 'leisure',

  /**
   * value: "association"
   * @const
   */
  association: 'association',

  /**
   * value: "other"
   * @const
   */
  other: 'other',
};

export default EventRetrieve;
