/**
 * API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unknown
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EventList model module.
 * @module model/EventList
 * @version unknown
 */
class EventList {
  /**
   * Constructs a new <code>EventList</code>.
   * @alias module:model/EventList
   * @param start {Date}
   * @param end {Date}
   */
  constructor(start, end) {
    EventList.initialize(this, start, end);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, start, end) {
    obj['start'] = start;
    obj['end'] = end;
  }

  /**
   * Constructs a <code>EventList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventList} obj Optional instance to populate.
   * @return {module:model/EventList} The populated <code>EventList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EventList();

      if (data.hasOwnProperty('pk')) {
        obj['pk'] = ApiClient.convertToType(data['pk'], 'Number');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('start')) {
        obj['start'] = ApiClient.convertToType(data['start'], 'Date');
      }
      if (data.hasOwnProperty('end')) {
        obj['end'] = ApiClient.convertToType(data['end'], 'Date');
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = ApiClient.convertToType(data['location'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'String');
      }
      if (data.hasOwnProperty('registered')) {
        obj['registered'] = ApiClient.convertToType(data['registered'], 'String');
      }
      if (data.hasOwnProperty('present')) {
        obj['present'] = ApiClient.convertToType(data['present'], 'String');
      }
      if (data.hasOwnProperty('pizza')) {
        obj['pizza'] = ApiClient.convertToType(data['pizza'], 'String');
      }
      if (data.hasOwnProperty('registration_allowed')) {
        obj['registration_allowed'] = ApiClient.convertToType(
          data['registration_allowed'],
          'String'
        );
      }
    }
    return obj;
  }
}

/**
 * @member {Number} pk
 */
EventList.prototype['pk'] = undefined;

/**
 * @member {String} title
 */
EventList.prototype['title'] = undefined;

/**
 * @member {String} description
 */
EventList.prototype['description'] = undefined;

/**
 * @member {Date} start
 */
EventList.prototype['start'] = undefined;

/**
 * @member {Date} end
 */
EventList.prototype['end'] = undefined;

/**
 * @member {String} location
 */
EventList.prototype['location'] = undefined;

/**
 * @member {String} price
 */
EventList.prototype['price'] = undefined;

/**
 * @member {String} registered
 */
EventList.prototype['registered'] = undefined;

/**
 * @member {String} present
 */
EventList.prototype['present'] = undefined;

/**
 * @member {String} pizza
 */
EventList.prototype['pizza'] = undefined;

/**
 * @member {String} registration_allowed
 */
EventList.prototype['registration_allowed'] = undefined;

export default EventList;
