/**
 * API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unknown
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MemberGroup model module.
 * @module model/MemberGroup
 * @version unknown
 */
class MemberGroup {
  /**
   * Constructs a new <code>MemberGroup</code>.
   * @alias module:model/MemberGroup
   * @param name {String}
   */
  constructor(name) {
    MemberGroup.initialize(this, name);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, name) {
    obj['name'] = name;
  }

  /**
   * Constructs a <code>MemberGroup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MemberGroup} obj Optional instance to populate.
   * @return {module:model/MemberGroup} The populated <code>MemberGroup</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MemberGroup();

      if (data.hasOwnProperty('pk')) {
        obj['pk'] = ApiClient.convertToType(data['pk'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('since')) {
        obj['since'] = ApiClient.convertToType(data['since'], 'Date');
      }
      if (data.hasOwnProperty('until')) {
        obj['until'] = ApiClient.convertToType(data['until'], 'Date');
      }
      if (data.hasOwnProperty('contact_address')) {
        obj['contact_address'] = ApiClient.convertToType(
          data['contact_address'],
          'String'
        );
      }
      if (data.hasOwnProperty('photo')) {
        obj['photo'] = ApiClient.convertToType(data['photo'], File);
      }
      if (data.hasOwnProperty('chair')) {
        obj['chair'] = ApiClient.convertToType(data['chair'], 'String');
      }
      if (data.hasOwnProperty('members')) {
        obj['members'] = ApiClient.convertToType(data['members'], 'String');
      }
    }
    return obj;
  }
}

/**
 * @member {Number} pk
 */
MemberGroup.prototype['pk'] = undefined;

/**
 * @member {String} name
 */
MemberGroup.prototype['name'] = undefined;

/**
 * @member {String} type
 */
MemberGroup.prototype['type'] = undefined;

/**
 * @member {Date} since
 */
MemberGroup.prototype['since'] = undefined;

/**
 * @member {Date} until
 */
MemberGroup.prototype['until'] = undefined;

/**
 * @member {String} contact_address
 */
MemberGroup.prototype['contact_address'] = undefined;

/**
 * @member {File} photo
 */
MemberGroup.prototype['photo'] = undefined;

/**
 * @member {String} chair
 */
MemberGroup.prototype['chair'] = undefined;

/**
 * @member {String} members
 */
MemberGroup.prototype['members'] = undefined;

export default MemberGroup;
