/**
 * API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unknown
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Order model module.
 * @module model/Order
 * @version unknown
 */
class Order {
  /**
   * Constructs a new <code>Order</code>.
   * @alias module:model/Order
   * @param product {Number}
   */
  constructor(product) {
    Order.initialize(this, product);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, product) {
    obj['product'] = product;
  }

  /**
   * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Order} obj Optional instance to populate.
   * @return {module:model/Order} The populated <code>Order</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Order();

      if (data.hasOwnProperty('pk')) {
        obj['pk'] = ApiClient.convertToType(data['pk'], 'Number');
      }
      if (data.hasOwnProperty('payment')) {
        obj['payment'] = ApiClient.convertToType(data['payment'], 'String');
      }
      if (data.hasOwnProperty('product')) {
        obj['product'] = ApiClient.convertToType(data['product'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('member')) {
        obj['member'] = ApiClient.convertToType(data['member'], 'String');
      }
    }
    return obj;
  }
}

/**
 * @member {Number} pk
 */
Order.prototype['pk'] = undefined;

/**
 * @member {module:model/Order.PaymentEnum} payment
 */
Order.prototype['payment'] = undefined;

/**
 * @member {Number} product
 */
Order.prototype['product'] = undefined;

/**
 * Use this for non-members
 * @member {String} name
 */
Order.prototype['name'] = undefined;

/**
 * @member {String} member
 */
Order.prototype['member'] = undefined;

/**
 * Allowed values for the <code>payment</code> property.
 * @enum {String}
 * @readonly
 */
Order['PaymentEnum'] = {
  /**
   * value: "cash_payment"
   * @const
   */
  cash_payment: 'cash_payment',

  /**
   * value: "card_payment"
   * @const
   */
  card_payment: 'card_payment',

  /**
   * value: "tpay_payment"
   * @const
   */
  tpay_payment: 'tpay_payment',

  /**
   * value: "wire_payment"
   * @const
   */
  wire_payment: 'wire_payment',

  /**
   * value: "no_payment"
   * @const
   */
  no_payment: 'no_payment',
};

export default Order;
