/**
 * API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unknown
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PartnerEvent model module.
 * @module model/PartnerEvent
 * @version unknown
 */
class PartnerEvent {
  /**
   * Constructs a new <code>PartnerEvent</code>.
   * @alias module:model/PartnerEvent
   * @param start {Date}
   * @param end {Date}
   * @param url {String}
   */
  constructor(start, end, url) {
    PartnerEvent.initialize(this, start, end, url);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, start, end, url) {
    obj['start'] = start;
    obj['end'] = end;
    obj['url'] = url;
  }

  /**
   * Constructs a <code>PartnerEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PartnerEvent} obj Optional instance to populate.
   * @return {module:model/PartnerEvent} The populated <code>PartnerEvent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PartnerEvent();

      if (data.hasOwnProperty('pk')) {
        obj['pk'] = ApiClient.convertToType(data['pk'], 'Number');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('start')) {
        obj['start'] = ApiClient.convertToType(data['start'], 'Date');
      }
      if (data.hasOwnProperty('end')) {
        obj['end'] = ApiClient.convertToType(data['end'], 'Date');
      }
      if (data.hasOwnProperty('location')) {
        obj['location'] = ApiClient.convertToType(data['location'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
    }
    return obj;
  }
}

/**
 * @member {Number} pk
 */
PartnerEvent.prototype['pk'] = undefined;

/**
 * @member {String} title
 */
PartnerEvent.prototype['title'] = undefined;

/**
 * @member {String} description
 */
PartnerEvent.prototype['description'] = undefined;

/**
 * @member {Date} start
 */
PartnerEvent.prototype['start'] = undefined;

/**
 * @member {Date} end
 */
PartnerEvent.prototype['end'] = undefined;

/**
 * @member {String} location
 */
PartnerEvent.prototype['location'] = undefined;

/**
 * @member {String} url
 */
PartnerEvent.prototype['url'] = undefined;

export default PartnerEvent;
