/**
 * API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unknown
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Pizza model module.
 * @module model/Pizza
 * @version unknown
 */
class Pizza {
  /**
   * Constructs a new <code>Pizza</code>.
   * @alias module:model/Pizza
   * @param name {String}
   * @param price {String}
   */
  constructor(name, price) {
    Pizza.initialize(this, name, price);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, name, price) {
    obj['name'] = name;
    obj['price'] = price;
  }

  /**
   * Constructs a <code>Pizza</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Pizza} obj Optional instance to populate.
   * @return {module:model/Pizza} The populated <code>Pizza</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Pizza();

      if (data.hasOwnProperty('pk')) {
        obj['pk'] = ApiClient.convertToType(data['pk'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = ApiClient.convertToType(data['price'], 'String');
      }
      if (data.hasOwnProperty('available')) {
        obj['available'] = ApiClient.convertToType(data['available'], 'Boolean');
      }
    }
    return obj;
  }
}

/**
 * @member {Number} pk
 */
Pizza.prototype['pk'] = undefined;

/**
 * @member {String} name
 */
Pizza.prototype['name'] = undefined;

/**
 * @member {String} description
 */
Pizza.prototype['description'] = undefined;

/**
 * @member {String} price
 */
Pizza.prototype['price'] = undefined;

/**
 * @member {Boolean} available
 */
Pizza.prototype['available'] = undefined;

export default Pizza;
