update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs a build"
  lane :build do
    sync_code_signing(type: "development")
    build_app(workspace: "ThaliApp.xcworkspace", scheme: "ThaliApp")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number({
      xcodeproj: "ThaliApp.xcodeproj",
      build_number: latest_testflight_build_number + 1
    })
    sync_code_signing(type: "appstore")
    build_app(workspace: "ThaliApp.xcworkspace", scheme: "ThaliApp")
    upload_to_testflight
  end

  desc "Push a new build to the App Store"
  lane :deploy do
    increment_build_number({
      xcodeproj: "ThaliApp.xcodeproj",
      build_number: app_store_build_number + 1
    })
    sync_code_signing(type: "appstore")
    build_app(workspace: "ThaliApp.xcworkspace", scheme: "ThaliApp")
    upload_to_app_store(
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      automatic_release: true
    )
  end
end
