/**
 * API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unknown
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2002 from '../model/InlineResponse2002';
import MemberList from '../model/MemberList';
import ProfileEdit from '../model/ProfileEdit';

/**
 * Members service.
 * @module api/MembersApi
 * @version unknown
 */
export default class MembersApi {
  /**
   * Constructs a new MembersApi.
   * @alias module:api/MembersApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * Viewset that renders or edits a member
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/MemberList} and HTTP response
   */
  birthdaysMemberWithHttpInfo() {
    let postBody = null;

    let pathParams = {};
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = ['oauth2'];
    let contentTypes = [];
    let accepts = ['application/json'];
    let returnType = MemberList;
    return this.apiClient.callApi(
      '/api/v1/members/birthdays/',
      'GET',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Viewset that renders or edits a member
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/MemberList}
   */
  birthdaysMember() {
    return this.birthdaysMemberWithHttpInfo().then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Viewset that renders or edits a member
   * @param {Object} opts Optional parameters
   * @param {Number} opts.limit Number of results to return per page.
   * @param {Number} opts.offset The initial index from which to return the results.
   * @param {String} opts.ordering Which field to use when ordering the results.
   * @param {String} opts.search A search term.
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse2002} and HTTP response
   */
  listMembersWithHttpInfo(opts) {
    opts = opts || {};
    let postBody = null;

    let pathParams = {};
    let queryParams = {
      limit: opts['limit'],
      offset: opts['offset'],
      ordering: opts['ordering'],
      search: opts['search'],
    };
    let headerParams = {};
    let formParams = {};

    let authNames = ['oauth2'];
    let contentTypes = [];
    let accepts = ['application/json'];
    let returnType = InlineResponse2002;
    return this.apiClient.callApi(
      '/api/v1/members/',
      'GET',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Viewset that renders or edits a member
   * @param {Object} opts Optional parameters
   * @param {Number} opts.limit Number of results to return per page.
   * @param {Number} opts.offset The initial index from which to return the results.
   * @param {String} opts.ordering Which field to use when ordering the results.
   * @param {String} opts.search A search term.
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse2002}
   */
  listMembers(opts) {
    return this.listMembersWithHttpInfo(opts).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Viewset that renders or edits a member
   * @param {String} id A unique integer value identifying this member.
   * @param {Object} opts Optional parameters
   * @param {String} opts.ordering Which field to use when ordering the results.
   * @param {String} opts.search A search term.
   * @param {module:model/ProfileEdit} opts.profileEdit
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ProfileEdit} and HTTP response
   */
  partialUpdateMemberWithHttpInfo(id, opts) {
    opts = opts || {};
    let postBody = opts['profileEdit'];
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error(
        "Missing the required parameter 'id' when calling partialUpdateMember"
      );
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {
      ordering: opts['ordering'],
      search: opts['search'],
    };
    let headerParams = {};
    let formParams = {};

    let authNames = ['oauth2'];
    let contentTypes = [
      'application/json',
      'application/x-www-form-urlencoded',
      'multipart/form-data',
    ];
    let accepts = ['application/json'];
    let returnType = ProfileEdit;
    return this.apiClient.callApi(
      '/api/v1/members/{id}/',
      'PATCH',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Viewset that renders or edits a member
   * @param {String} id A unique integer value identifying this member.
   * @param {Object} opts Optional parameters
   * @param {String} opts.ordering Which field to use when ordering the results.
   * @param {String} opts.search A search term.
   * @param {module:model/ProfileEdit} opts.profileEdit
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ProfileEdit}
   */
  partialUpdateMember(id, opts) {
    return this.partialUpdateMemberWithHttpInfo(id, opts).then(function (
      response_and_data
    ) {
      return response_and_data.data;
    });
  }

  /**
   * Viewset that renders or edits a member
   * @param {String} id A unique integer value identifying this member.
   * @param {Object} opts Optional parameters
   * @param {String} opts.ordering Which field to use when ordering the results.
   * @param {String} opts.search A search term.
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ProfileEdit} and HTTP response
   */
  retrieveMemberWithHttpInfo(id, opts) {
    opts = opts || {};
    let postBody = null;
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error(
        "Missing the required parameter 'id' when calling retrieveMember"
      );
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {
      ordering: opts['ordering'],
      search: opts['search'],
    };
    let headerParams = {};
    let formParams = {};

    let authNames = ['oauth2'];
    let contentTypes = [];
    let accepts = ['application/json'];
    let returnType = ProfileEdit;
    return this.apiClient.callApi(
      '/api/v1/members/{id}/',
      'GET',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Viewset that renders or edits a member
   * @param {String} id A unique integer value identifying this member.
   * @param {Object} opts Optional parameters
   * @param {String} opts.ordering Which field to use when ordering the results.
   * @param {String} opts.search A search term.
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ProfileEdit}
   */
  retrieveMember(id, opts) {
    return this.retrieveMemberWithHttpInfo(id, opts).then(function (response_and_data) {
      return response_and_data.data;
    });
  }

  /**
   * Viewset that renders or edits a member
   * @param {String} id A unique integer value identifying this member.
   * @param {Object} opts Optional parameters
   * @param {String} opts.ordering Which field to use when ordering the results.
   * @param {String} opts.search A search term.
   * @param {module:model/ProfileEdit} opts.profileEdit
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ProfileEdit} and HTTP response
   */
  updateMemberWithHttpInfo(id, opts) {
    opts = opts || {};
    let postBody = opts['profileEdit'];
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error("Missing the required parameter 'id' when calling updateMember");
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {
      ordering: opts['ordering'],
      search: opts['search'],
    };
    let headerParams = {};
    let formParams = {};

    let authNames = ['oauth2'];
    let contentTypes = [
      'application/json',
      'application/x-www-form-urlencoded',
      'multipart/form-data',
    ];
    let accepts = ['application/json'];
    let returnType = ProfileEdit;
    return this.apiClient.callApi(
      '/api/v1/members/{id}/',
      'PUT',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Viewset that renders or edits a member
   * @param {String} id A unique integer value identifying this member.
   * @param {Object} opts Optional parameters
   * @param {String} opts.ordering Which field to use when ordering the results.
   * @param {String} opts.search A search term.
   * @param {module:model/ProfileEdit} opts.profileEdit
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ProfileEdit}
   */
  updateMember(id, opts) {
    return this.updateMemberWithHttpInfo(id, opts).then(function (response_and_data) {
      return response_and_data.data;
    });
  }
}
