/**
 * API v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: unknown
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EventRegistration from '../model/EventRegistration';

/**
 * Registrations service.
 * @module api/RegistrationsApi
 * @version unknown
 */
export default class RegistrationsApi {
  /**
   * Constructs a new RegistrationsApi.
   * @alias module:api/RegistrationsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  constructor(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;
  }

  /**
   * Defines the viewset for registrations, requires an authenticated user. Has custom update and destroy methods that use the services.
   * @param {String} id A unique integer value identifying this Registration.
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
   */
  destroyEventRegistrationWithHttpInfo(id) {
    let postBody = null;
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error(
        "Missing the required parameter 'id' when calling destroyEventRegistration"
      );
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = [];
    let returnType = null;
    return this.apiClient.callApi(
      '/api/v1/registrations/{id}/',
      'DELETE',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Defines the viewset for registrations, requires an authenticated user. Has custom update and destroy methods that use the services.
   * @param {String} id A unique integer value identifying this Registration.
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}
   */
  destroyEventRegistration(id) {
    return this.destroyEventRegistrationWithHttpInfo(id).then(function (
      response_and_data
    ) {
      return response_and_data.data;
    });
  }

  /**
   * Defines the viewset for registrations, requires an authenticated user. Has custom update and destroy methods that use the services.
   * @param {String} id A unique integer value identifying this Registration.
   * @param {Object} opts Optional parameters
   * @param {module:model/EventRegistration} opts.eventRegistration
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EventRegistration} and HTTP response
   */
  partialUpdateEventRegistrationWithHttpInfo(id, opts) {
    opts = opts || {};
    let postBody = opts['eventRegistration'];
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error(
        "Missing the required parameter 'id' when calling partialUpdateEventRegistration"
      );
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [
      'application/json',
      'application/x-www-form-urlencoded',
      'multipart/form-data',
    ];
    let accepts = ['application/json'];
    let returnType = EventRegistration;
    return this.apiClient.callApi(
      '/api/v1/registrations/{id}/',
      'PATCH',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Defines the viewset for registrations, requires an authenticated user. Has custom update and destroy methods that use the services.
   * @param {String} id A unique integer value identifying this Registration.
   * @param {Object} opts Optional parameters
   * @param {module:model/EventRegistration} opts.eventRegistration
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EventRegistration}
   */
  partialUpdateEventRegistration(id, opts) {
    return this.partialUpdateEventRegistrationWithHttpInfo(id, opts).then(function (
      response_and_data
    ) {
      return response_and_data.data;
    });
  }

  /**
   * Defines the viewset for registrations, requires an authenticated user. Has custom update and destroy methods that use the services.
   * @param {String} id A unique integer value identifying this Registration.
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EventRegistration} and HTTP response
   */
  retrieveEventRegistrationWithHttpInfo(id) {
    let postBody = null;
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error(
        "Missing the required parameter 'id' when calling retrieveEventRegistration"
      );
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [];
    let accepts = ['application/json'];
    let returnType = EventRegistration;
    return this.apiClient.callApi(
      '/api/v1/registrations/{id}/',
      'GET',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Defines the viewset for registrations, requires an authenticated user. Has custom update and destroy methods that use the services.
   * @param {String} id A unique integer value identifying this Registration.
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EventRegistration}
   */
  retrieveEventRegistration(id) {
    return this.retrieveEventRegistrationWithHttpInfo(id).then(function (
      response_and_data
    ) {
      return response_and_data.data;
    });
  }

  /**
   * Defines the viewset for registrations, requires an authenticated user. Has custom update and destroy methods that use the services.
   * @param {String} id A unique integer value identifying this Registration.
   * @param {Object} opts Optional parameters
   * @param {module:model/EventRegistration} opts.eventRegistration
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EventRegistration} and HTTP response
   */
  updateEventRegistrationWithHttpInfo(id, opts) {
    opts = opts || {};
    let postBody = opts['eventRegistration'];
    // verify the required parameter 'id' is set
    if (id === undefined || id === null) {
      throw new Error(
        "Missing the required parameter 'id' when calling updateEventRegistration"
      );
    }

    let pathParams = {
      id: id,
    };
    let queryParams = {};
    let headerParams = {};
    let formParams = {};

    let authNames = [];
    let contentTypes = [
      'application/json',
      'application/x-www-form-urlencoded',
      'multipart/form-data',
    ];
    let accepts = ['application/json'];
    let returnType = EventRegistration;
    return this.apiClient.callApi(
      '/api/v1/registrations/{id}/',
      'PUT',
      pathParams,
      queryParams,
      headerParams,
      formParams,
      postBody,
      authNames,
      contentTypes,
      accepts,
      returnType,
      null
    );
  }

  /**
   * Defines the viewset for registrations, requires an authenticated user. Has custom update and destroy methods that use the services.
   * @param {String} id A unique integer value identifying this Registration.
   * @param {Object} opts Optional parameters
   * @param {module:model/EventRegistration} opts.eventRegistration
   * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EventRegistration}
   */
  updateEventRegistration(id, opts) {
    return this.updateEventRegistrationWithHttpInfo(id, opts).then(function (
      response_and_data
    ) {
      return response_and_data.data;
    });
  }
}
